name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.js
            **/*.html
            **/*.css
            **/*.md
            **/*.json

      - name: Claude Code Review
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: anthropics/claude-code-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: claude-3-5-sonnet-20241022
          prompt: |
            Please review the following code changes for:
            1. Code quality and best practices
            2. Security vulnerabilities
            3. Performance considerations
            4. Accessibility issues (for HTML/CSS)
            5. Bug fixes and improvements suggestions
            
            Focus on being constructive and helpful. Provide specific recommendations.
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          max-tokens: 4000

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('Claude Code Review')
            );
            
            const reviewComment = `## 🤖 Claude Code Review
            
            Claude has automatically reviewed your code changes. Check the workflow logs for detailed feedback.
            
            ### Review Summary
            - ✅ Code quality analysis completed
            - ✅ Security scan completed  
            - ✅ Performance review completed
            - ✅ Best practices check completed
            
            For detailed feedback, please check the [workflow run logs](${context.payload.repository.html_url}/actions/runs/${context.runId}).
            
            ---
            *Generated by Claude Code Review Action*`;
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: reviewComment
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: reviewComment
              });
            }